# Generated by Django 2.0.10 on 2019-01-13 12:02

import JUApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JUApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=100)),
                ('resource', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to=JUApp.models.getPath)),
            ],
        ),
    ]
