# Generated by Django 2.0.10 on 2019-01-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JUApp', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
