# Generated by Django 2.0.10 on 2019-01-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JUApp', '0004_user_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
